create wt.js add html & css for work-together section
yuliia-shl/js-project-team-10 pull request #3
Opened 2024-10-10 12:02 UTC by Sashko-kapillar

2024-10-10 15:28 UTC, yuliia-shl requested changes
Підкорегувати стилі

2024-10-10 16:50 UTC, yuliia-shl requested changes

2024-10-10 16:50 UTC, yuliia-shl commented on src/partials/work-together.html
> +<section id="work-together">
додати клас section, щоб додалися глобальні стилі

2024-10-10 16:50 UTC, yuliia-shl commented on src/css/work-together.css
> +  padding: 40px 20px;
видалити, бо коли додаiш глобальний клас section - це не потрібно. Паддінги по боках вказані в класі container

2024-10-10 16:50 UTC, yuliia-shl commented on src/css/work-together.css
> +  gap: 10px;
має бути 16px

2024-10-10 16:50 UTC, yuliia-shl commented on src/css/work-together.css
> +  margin-bottom: 10px;
видалити

2024-10-10 16:50 UTC, yuliia-shl commented on src/css/work-together.css
> +  margin-right: 10px;
видалити

2024-10-10 16:50 UTC, yuliia-shl commented on src/css/work-together.css
> +  margin-bottom: 20px;
має бути 40пкс

2024-10-10 16:50 UTC, yuliia-shl commented on src/partials/work-together.html
> +            <use href="./img/icon.svg#icon-phone"></use>
іконки не відповідають макету (дуже замальовані зеленим)

2024-10-10 16:50 UTC, yuliia-shl commented on src/css/work-together.css
> +  background-color: #f9f9f9;
згідно макету background: #e4e5e6;
колір тексту в інпуті (Placeholder) має бути темніший #292929

2024-10-10 16:50 UTC, yuliia-shl commented on src/js/work-together.js
> +  event.preventDefault();
при відправці форми сторінка перезавантажується і не вискакує вікно про успіх

2024-10-10 17:16 UTC, Sashko-kapillar commented on src/js/work-together.js
> +  event.preventDefault();
не був підключений js до main.js

2024-10-10 18:11 UTC, Sashko-kapillar commented on src/css/work-together.css
> +  background-color: #f9f9f9;
ок

2024-10-10 18:11 UTC, Sashko-kapillar commented on src/partials/work-together.html
> +            <use href="./img/icon.svg#icon-phone"></use>
ок

2024-10-10 18:12 UTC, Sashko-kapillar commented on src/css/work-together.css
> +  margin-bottom: 20px;
ок

2024-10-10 21:32 UTC, Sashko-kapillar commented on src/css/work-together.css
> +  padding: 40px 20px;
видалив

2024-10-10 21:33 UTC, Sashko-kapillar commented on src/css/work-together.css
> +  margin-right: 10px;
видалив

2024-10-11 11:04 UTC, Sashko-kapillar reviewed
??

2024-10-11 12:15 UTC, yuliia-shl approved these changes

2024-10-11 12:15 UTC, merged